# Generated by Django 5.1.6 on 2025-02-18 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='state',
            new_name='county',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='notes',
        ),
    ]
